### ISSUE TITLE
2 issues 

### ISSUE THREAD

**Issue by Asap2024** [Swag1400/exeter-selfbot-beta#26]
When i go to terminal and do pip install [dependency] doesnt work but if i do it without brackets works. Then why i cd then the file and try to python exeter.py it tells me that line 15 in module from bs4 import beautifulsoup as bs4 says its not found

**Comment by owolo** [comment]
you can install modules without brackets only, since you don't need them and for second issue type `pip install beautifulsoup4` or `pip install bs4` (does the same thing)
