### ISSUE TITLE
token logger + skidded alucard

### ISSUE THREAD

**Issue by 2tacey** [Swag1400/exeter-selfbot-beta#4]

**Comment by pani7777** [comment]
Not sure if this is skidded, but YOU skidded a selfbot.

https://github.com/2tacey/22tacey-selfbot
  "name": "asari-selfbot-master",
  "version": "1.0.0",
  "description": "selfbot.cc but with better performance &amp; made in NodeJS",
  clearly taken from user outlaylol's selfbot...
